### ISSUE TITLE
give some advice on installing Oxcal

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/oxcAAR#14]
Hi @MartinHinz !

I want to calibrate dates from your RADON database in R and struggle with installing Oxcal. Do you plan to have a small intro into installing Oxcal on different OS? If so, where would be the place to put these information?

**Comment by nevrome** [comment]
Pls try `quickSetupOxcal()`. There's definitely a need for more and better documentation right now. Maybe something like a quickstart guide in the README.

**Comment by dakni** [comment]
nice. thanks. I'll try

**Comment by dakni** [comment]
quickSetupOxcal() works great! :) now everything is clear.
