### ISSUE TITLE
make it run under windows

### ISSUE THREAD

**Issue by MartinHinz** [ISAAKiel/oxcAAR#2]
oxcAAR is currently not running under windows. @MoritzMennenga had tested it some time ago, the error was related to path names resp. spaces in them under windows.

There must be general better ways to implement external programs into R, is there a best practise that works under all OS?

**Comment by nevrome** [comment]
I don't know if this is comparable, but for [rdoxygen](https://github.com/nevrome/rdoxygen) I call doxygen via `system()` after checking if doxygen is in the system path. 

```
check_for_doxygen <- function(){
  return(nchar(Sys.which("doxygen")) > 0)
}
```

**Comment by MartinHinz** [comment]
Done thanks to @nevrome !
