### ISSUE TITLE
Last Check before Release of 1.1 Flora

### ISSUE THREAD

**Issue by MartinHinz** [ISAAKiel/oxcAAR#36]
Checking the changes and the functionality, as well as al necessities for an cran release of 1.1 Flora

**Comment by MartinHinz** [comment]
* Updated cran-comments.md and and NEWS.txt
* Updated DESCRIPTION

What else is left to do before submission to CRAN?

**Comment by MartinHinz** [comment]
@nevrome, what do you think, what is still open to resubmit?

**Comment by nevrome** [comment]
See our c14bazAAR pre-submission list here: https://github.com/ropensci/c14bazAAR#pre-submision-testing

**Comment by MartinHinz** [comment]
- [ ] The package works and all functions are usable
- [ ] The package documentation is up-to-date and represents the functions correctly
- [ ] The test coverage of the package functions is sufficient
- [ ] DESCRIPTION is up-to-date with the latest version number and database list
- [ ] README.md is up-to-date
- [ ] NEWS.md is up-to-date and includes the latest changes
- [ ] Package checks ran and did not yield any ERRORS, WARNINGS or NOTES (or at least the NOTES are addressed in the cran-comments.md)
  - [ ] locally (devtools::check())
  - [ ] rhub (devtools::check_rhub(email = ...))
  - [ ] winbuilder (devtools::check_win_release(email = ....) + devtools::check_win_devel(email = ....))
- [ ] Spellcheck with devtools::spell_check() ran and did yield not only false-positives
- [ ] codemeta.json is up-to-date (can be updated with codemetar::write_codemeta())
- [ ] inst/CITATION is up-to-date
- [ ] The package does not make external changes without explicit user permission. It does not write to the file system, change options, install packages, quit R, send information over the internet, open external software, etc.
- [ ] No reverse dependencies break because of the new package version (devtools::revdep_check())

**Comment by MartinHinz** [comment]
Thanks! I think, with checking every of those boxes, the message is "We are good to go"? Any other suggestions?

**Comment by MartinHinz** [comment]
All engine go for Release of oxcAAR 1.1 Flora
