### ISSUE TITLE
Allow to select the output directory in executeOxcalScript

### ISSUE THREAD

**Issue by nfrerebeau** [ISAAKiel/oxcAAR#42]
When running an OxCal script with `executeOxcalScript()`, the output files are generated in a temporary directory. Would it be possible to let the user choose the output directory (with a default value to `tempfile()`)?

This could be useful when you want to keep specific files (e.g. the csv produced by `MCMC_Sample();`).

**Comment by MartinHinz** [comment]
Thank you for the very useful suggestion! I think this is possible! Will put that on the agenda.
