### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by MartinHinz** [ISAAKiel/oxcAAR#8]
The documentation should be checked in respect to comprehensibility and language. The vignette might also be improved to reflect all the possibilities that this fine package offers.
When done from the functional point of view, @ctietze91 might also proofread it again?

**Comment by ctietze91** [comment]
Sure I can do that, but I'm going to hold the corrections until my 'check-problem' is fixed.

**Comment by MartinHinz** [comment]
Perfect, expecting that. As you see above, was planned that way :-)

**Comment by MartinHinz** [comment]
@ctietze91, now might be a good time to start proof reading, if you like?

**Comment by ctietze91** [comment]
okay so I wanted to push my changes for the basic-usage.rmd but my r tellls me that there is a problem in line 24-29, which I didnt touch. Did this occur to anybody else? (im supposed to be up-to-date on the package, according to my r)

**Comment by nevrome** [comment]
That's not a very [useful bugreport](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) ;-)

I guess you got this error when you tried to knit the vignette. Can you try to run the R code in the lines 24-29 and provide the result? Maybe you didn't setup Oxcal correctly. The fastest way to do this is to call `oxcAAR::quickSetupOxcal()`.

**Comment by ctietze91** [comment]
Sorry. I know. So here it goes:

This is the error I get when knitting, it is similar to what happens when I try to check.

![image](https://user-images.githubusercontent.com/26183035/29890450-ec372dde-8dc7-11e7-864f-0d5f343b7b1e.png)

**Comment by nevrome** [comment]
Haha - I don't know how I missed that yesterday. This can't work on Windows. @MartinHinz probably only had linux in mind when he wrote this.

I would suggest to change the paragraph to something like this:

***

Lets assume, we want to calibrate a date 5000 BP +- 25 years. `oxcAAR` has the function `oxcalCalibrate` for doing so. But at first we have to load the package and setup OxCal (or tell `oxcAAR` where to find the local path to OxCal). Than you can calibrate the date using bp, std and name.

```r
library(oxcAAR)
quickSetupOxcal()
#setOxcalExecutablePath("~/OxCal/bin/OxCalLinux")
my_date <- oxcalCalibrate(5000,25,"KIA-12345")
my_date
plot(my_date)
```

***

Btw. is it "Oxcal" or "OxCal"?

**Comment by ctietze91** [comment]
It doesn't work. He wants to set the path and is complaining that he cant. Didn't @quassinja try the wohl thing with her laptop and said it worked? Or am I mixing something up?

**Comment by nevrome** [comment]
Maybe a user permission problem? Do you get an error message? Could you try to download OxCal manually and call `setOxcalExecutablePath("path/to/your/OxCal/bin/OxCalWin.exe")`? Maybe it's best to meet with @MartinHinz in person to debug this.

@MoritzMennenga & @quassinja Would you mind testing `quickSetupOxcal()` on your windows systems?

**Comment by MoritzMennenga** [comment]
The Quicksetup works fine, but then I got a problem while calibrating (I started RStudio in Adminiistrator mode)
```
> install_github('ISAAKiel/oxcAAR')
Downloading GitHub repo ISAAKiel/oxcAAR@master
from URL https://api.github.com/repos/ISAAKiel/oxcAAR/zipball/master
Installing oxcAAR
"D:/R/R-3.4.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/mo1005.NIHK/AppData/Local/Temp/RtmpqoCQWz/devtools3a74778e5f71/ISAAKiel-oxcAAR-c1f08f0"  \
  --library="C:/Users/mo1005.NIHK/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'oxcAAR' ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (oxcAAR)
> library(oxcAAR)
> quickSetupOxcal()
Oxcal doesn't seem to be installed. Downloading it now:
trying URL 'https://c14.arch.ox.ac.uk/OxCalDistribution.zip'
Content type 'application/zip' length 3086046 bytes (2.9 MB)
downloaded 2.9 MB

Oxcal download to C:\Users\mo1005.NIHK\Documents successful!
Oxcal path set!
NULL
> my_date <- oxcalCalibrate(5000,25,"KIA-12345")
OxCal v4.3.2 (c) Bronk Ramsey (2017)
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\MO1005~1.NIH\AppData\Local\Temp\RtmpqoCQWz\file3a742e962756.js': No such file or directory
```

**Comment by MoritzMennenga** [comment]
Second try with my libPath (not the standart one)
```
> library(oxcAAR)
> quickSetupOxcal()
OxCal v4.3.2 (c) Bronk Ramsey (2017)
Oxcal is installed but Oxcal executable path is wrong. Let's have a look...
Oxcal path set!
NULL
> setOxcalExecutablePath("C:\\Users\\mo1005.NIHK\\Documents\\OxCal\\bin\\OxCalWin.exe")
Oxcal path set!
> my_date <- oxcalCalibrate(5000,25,"KIA-12345")
OxCal v4.3.2 (c) Bronk Ramsey (2017)
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\MO1005~1.NIH\AppData\Local\Temp\RtmpqoCQWz\file3a7422026d3f.js': No such file or directory
```

**Comment by nevrome** [comment]
Thanks for the nice bug report Moritz. Your error seems to be different from the one @ctietze91 gets. Could you check if `C:\Users\MO1005~1.NIH\AppData\Local\Temp\` is a correct path and run the whole thing without administrator permissions?

Maybe there's something fishy going on here
https://github.com/ISAAKiel/oxcAAR/blob/c1f08f092778dddabd98abb10711df09616af330/R/executeOxcalScript.R#L15
and we can't see it, because the output is suppressed. Then this 
https://github.com/ISAAKiel/oxcAAR/blob/c1f08f092778dddabd98abb10711df09616af330/R/oxcalCalibrate.R#L13
throws an error. 

I stole my brothers windows 7 laptop and tried to reproduce your errors. Unfortunately it works fine there.

**Comment by MoritzMennenga** [comment]
@nevrome 
The path exists.
Running it in normal mode causes the same error
```
> library(oxcAAR)
> quickSetupOxcal()
Oxcal is installed but Oxcal executable path is wrong. Let's have a look...
Oxcal path set!
NULL
> setOxcalExecutablePath("C:\\Users\\mo1005.NIHK\\Documents\\OxCal\\bin\\OxCalWin.exe")
Oxcal path set!
> my_date <- oxcalCalibrate(5000,25,"KIA-12345")
Error in file(file, "r") : cannot open the connection
In addition: Warning message:
In file(file, "r") :
  cannot open file 'C:\Users\MO1005~1.NIH\AppData\Local\Temp\Rtmp0sKvvb\file34682ebe5504.js': No such file or directory
```

**Comment by MoritzMennenga** [comment]
I will try it at home o my notebook later on. I made the experience, that sometimes stuff works on one Windows PC, but not on the other.

**Comment by quassinja** [comment]
I am sorry, just returned back to Kiel yesterday from Cologne. Wil try it with my computer in the evening, but the problem I had that @ctietze91 mentioned was something different and was solved in Berlin.

**Comment by nevrome** [comment]
@MoritzMennenga 

How does the temporary input file with the oxcal code look like after you run `oxcalCalibrate(5000,25,"KIA-12345")`? It's at the same location as the output file that is mentioned in the error (`C:\Users\MO1005~1.NIH\AppData\Local\Temp\Rtmp...\tempfile_name_without_point_js`). 

It's supposed to contain the following line: `R_Date("KIA-12345", 5000, 25);`

If this file is available and correctly written, then please try to call oxcal on it. Should work with something like this:
```
C:\Users\mo1005.NIHK\Documents\OxCal\bin\OxCalWin.exe C:\Users\MO1005~1.NIH\AppData\Local\Temp\Rtmp...\tempfile_name_without_point_js
```

Does this create `tempfile_name_with_point_js` (the file mentioned in the error) or do you get an error from OxCal here?

**Comment by MoritzMennenga** [comment]
Ok, it works fine on my laptop, lets see the differences:
destoppc: windows 7, RStudio-Version 1.0.136, R 3.4.1 64 bit
laptop: windows 8, RStudio-Version 1.0.153, R 3.4.1 64-bit

**Comment by ctietze91** [comment]
Okay so the quick session with Martin worked. Was able to push my changes. Could someone look into my [xxx] in the text?? Maybe @MartinHinz ?

**Comment by nevrome** [comment]
@ctietze91 What caused the issue and how did you solve it?

**Comment by ctietze91** [comment]
So the issue was really with my computer -.- . He didn't like the OxCal download. Only found out after I checked my security log. After I resolved this issue, the resolution with the quicksetup - version by @nevrome worked. Sorry for the mess.

**Comment by MartinHinz** [comment]
I do not see any [xxx] in the text! Is that correct, @ctietze91? If so, I declare the version 1.0 of oxcAAR open!
